### ISSUE TITLE
Usage of super-fields adds lumo-styles to the application

### ISSUE THREAD

**Issue by provi-dominik** [vaadin-miki/super-fields#528] opened 2024-10-07 16:01 UTC
If I add the SuperBigDecimalField (super-fields version 0.19.2) to my application with the Vaadin version 24.3.9 and Material-theme, these Lumo-styles are added:
![image](https://github.com/user-attachments/assets/3b0d0098-95d0-4ecc-bee6-c84a20c887d7)

These styles ruin the styling of my Material-themed application.
Is there a way to exclude these styles or can you provide a theme independent version of the super-fields?

**Comment by vaadin-miki** [comment] 2024-10-11 10:16
hi @provi-dominik and apologies for the delay in responding

I have not checked the behaviour of the app with different themes, to be honest, but that looks like a serious bug - as in general the things should be theme-independent, at least I would hope so

let me dig around this for a while and if I can find a fix, it will be in the next release :)

**Comment by vaadin-miki** [comment] 2024-10-18 13:20
@provi-dominik okay, so I did a bit of research and I am afraid this is not a superfields bug, but a Vaadin one

try creating a simple Vaadin app with one view (that extends `VerticalLayout`, for example), and something that implements `AppShellConfigurator` that has `@NoTheme` on it; when you run that up, the styles still contain `lumo-*-*` entries (see [mininum-example.zip](https://github.com/user-attachments/files/17436035/mininum-example.zip)), I used Vaadin 24.5.0 for that

it may be related to https://github.com/vaadin/flow/issues/16249 - if you can reproduce the behaviour I just described on your machine, I would suggest reporting a new issue to Vaadin Flow and include your minimum project there

**Comment by vaadin-miki** [comment] 2024-10-18 13:27
going to close this ticket, as it is outside of my reach to fix it (other than override a vaadin class responsible for generating imports, which I would rather not do for obvious reasons ;) )

**Closed by vaadin-miki** 2024-10-18 13:27 UTC
Labels: invalid
