### ISSUE TITLE
DecimalFormat divide /0 - SuperBigDecimalField

### ISSUE THREAD

**Issue by igorserraino** [vaadin-miki/super-fields#358] opened 2022-04-08 12:01 UTC
setting setDecimalFormat(new DecimalFormat("###E0"))
or any other pattern to view fields by an exponential (scientific) way

-> there's an error "divide /0" while loading view.

I'm using SuperBigDecimalField

**Comment by vaadin-miki** [comment] 2022-04-08 12:08
thanks for reporting the issue! I will look into it over the weekend

also, entering numbers with scientific notation is possible by calling `.setExponentSeparator(char)` - but definitely there should be no errors with decimal format

**Comment by igorserraino** [comment] 2022-04-08 12:17
thanks Miki
yes I'm using .setExponentSeparator(char) and the component works well, it parses the value as double.

Anyway my view reads a text file with double numbers in scientific or not scientific format as well. I need to format them always in exponential way inside the view, automatically when reading from a file.

**Comment by vaadin-miki** [comment] 2022-04-11 06:33
welp, this has to wait as more work has piled up and needs to be sorted out first - sorry for the delay, I promise to look into it as soon as I have time; if it is something I can fix it will be fixed in the next release

**Comment by vaadin-miki** [comment] 2022-04-13 08:03
alright, the error is caused by the new `DecimalFormat` object returning zero for `.getGroupingSize` - I guess it should default to `1`?

**Comment by igorserraino** [comment] 2022-04-13 08:12
> alright, the error is caused by the new `DecimalFormat` object returning zero for `.getGroupingSize` - I guess it should default to `1`?

hi Miki 
actually divide /0 is coming from .setDecimalFormat invoked on a SuperBigDecimalField object.
That's a java.lang.ArithmeticException: / by zero .

DecimalFormat constructor does not throw any exception of that kind so I guess the issue is inside the setDecimalFormat method.

Thanks for paying attention

**Comment by vaadin-miki** [comment] 2022-04-13 08:14
yup, problems are caused by the fact that the building of the regexp assumes certain things about the `DecimalFormat` object, which clearly are not happening when it is created manually and not obtained from the locale :) anyway, I should be able to fix it

**Comment by vaadin-miki** [comment] 2022-04-13 08:38
@igorserraino if you are fine with trying the code before it gets released, please check out branch `358-decimal-format-error` and see if things work the way you expect them to work :) (keep in mind bleeding edge uses a different version number)

I will leave the branch hanging for a few days, and if you find any related errors - please write in this ticket; thanks!

**Comment by igorserraino** [comment] 2022-04-13 08:51
> @igorserraino if you are fine with trying the code before it gets released, please check out branch `358-decimal-format-error` and see if things work the way you expect them to work :) (keep in mind bleeding edge uses a different version number)
> 
> I will leave the branch hanging for a few days, and if you find any related errors - please write in this ticket; thanks!

THANKS

**Comment by igorserraino** [comment] 2022-04-13 08:59
sorry miki is there a maven repo for this build-in-progress branch? It would be helpful to check it straight inside my web app

**Comment by vaadin-miki** [comment] 2022-04-13 09:02
no, sadly there is not :| also the tests fail due to some locale problems... *sigh*

but a good idea, I will consider making a nightly build or something

**Closed** 2022-04-19 07:52 UTC
Labels: bug
