### ISSUE TITLE
Cannot read property 'parseDate' of undefined

### ISSUE THREAD

**Issue by Darkoofthedark** [vaadin-miki/super-fields#305] opened 2021-07-23 14:54 UTC
The date picker element is not showing up on the page and throwing a javascript error in the browser console 2 times:

In Google Chrome, IE 11 and Edge :
"There seems to be an error in the Vaadin Date Picker:
Cannot read property 'parseDate' of undefined"

In Firefox :
"There seems to be an error in the Vaadin Date Picker:
i.i18n is undefined"

This instance of vaadin date picker is bundled inside a SuperDatePicker component. Even though it is the vaadin date picker throwing the error, I only get the error while using a SuperDatePicker in my code. If I use a normal vaadin date picker and configure them in the exact same way (without the date pattern which is not customizable with the built-in vaadin date picker), it works.

The component should work, I have a similar project using the same version of the date picker, same version of superfields, same date pattern and same version of vaadin and where it is configured in the same way without issues.

![image](https://user-images.githubusercontent.com/87864570/126798771-f58e78c4-ace6-416f-8b08-eaf7f4eaf98c.png)

![image](https://user-images.githubusercontent.com/87864570/126792998-58b97e28-80b3-4d3f-84b0-7c48ad65068f.png)

![image](https://user-images.githubusercontent.com/87864570/126800319-2c7c5b28-8c2d-429a-b756-789978a53c96.png)

### Snippet
```
SuperDatePicker startDatePicker = new SuperDatePicker();
startDatePicker.setId("client-admin-tabs-decisions_search-form_date-start");

DatePattern datePattern = new DatePattern();
datePattern.setDisplayOrder(Order.YEAR_MONTH_DAY);
datePattern.setSeparator('-');

startDatePicker.setDatePattern(datePattern);
startDatePicker.setPlaceholder("YYYY-MM-DD");
startDatePicker.setErrorMessage("Invalid date format");

SuperDatePicker endDatePicker = new SuperDatePicker();
endDatePicker.setId("client-admin-tabs-decisions_search-form_date-end");
endDatePicker.setDatePattern(datePattern);
endDatePicker.setPlaceholder("YYYY-MM-DD");
endDatePicker.setErrorMessage("Invalid date format");

HorizontalLayout dateRangeLayout = new HorizontalLayout();
dateRangeLayout.setSpacing(false);
dateRangeLayout.add(new Label("Date issued between"));

startDatePicker.setWidth("350px");
dateRangeLayout.add(startDatePicker);

Label andLabel = new Label(this.messageProvider.i18n("search-panel-date-and"));
HorizontalLayout andLayout = new HorizontalLayout("and");
andLayout.setWidth("100px");

dateRangeLayout.add(andLayout);

endDatePicker.setWidth("350px");
dateRangeLayout.add(endDatePicker);
this.add(dateRangeLayout);
```

### Steps to reproduce

The error should occur during the loading of the UI without any user input required.

### Environment
- Windows 10
- Eclipse 2020 IDE
- OpenJDK 13.0.2 (but project is compiling in Java 11)
- Using Vaadin 14.4.6
- Vaadin Date Picker 4.4.1
- org.vaadin.miki.superfields 0.10.2

### Browsers Affected
- Chrome
- Firefox
- IE 11
- Edge

**Comment by vaadin-miki** [comment] 2021-08-02 06:37
This has to be the prettiest and most detailed bug report I have ever received 😍

It looks like the problem is related to how the component is initialised (server side calls the client side before it is ready) - perhaps something was changed in the recent Vaadin version, or your case happens to be a corner case of setting date patterns that I did not take into account. Anyway, will look into this in the coming days.

**Comment by vaadin-miki** [comment] 2021-08-02 10:13
The snippet alone works fine, so the problem is elsewhere. From the screenshots (and html inspector) it looks like the date pickers reside inside a tabsheet of sorts - most likely that is causing the problem. Could you please share more code on how displaying tabs works? If not, could you please try the same solution with `SuperTabs`, which are also a part of SuperFields, and see if it helps? :)

**Comment by vaadin-miki** [comment] 2021-08-10 10:49
this has now its own separate branch, `305-parse-date-error`, and a dedicated page in the demo app, `/bug-305` that contains the code from the snippet from the description above

it works, so I am not sure how can I proceed with it - I am going to close this ticket, but if a more reproducable code will be provided, this ticket can be reopened and work can continue

**Closed** 2021-08-10 10:49 UTC
Labels: bug, help wanted, question

**Comment by Darkoofthedark** [comment] 2021-08-10 16:43
After rebuilding my vaadin frontend and clearing some old dependencies the bug stopped occurring and has not happened since. I am unsure what changed but it seems I am also unable to reproduce it.
