### ISSUE TITLE
CSS error

### ISSUE THREAD

**Issue by alabotski** [vaadin-miki/super-fields#381] opened 2022-05-23 17:29 UTC
I use 0.13.1  and vaadin Version=23.0.9

Error

```
Execution failed for task ':vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Error occured during goal execution: 
  
    Failed to find the following css files in the `node_modules` or `/Users/alex/Workspace/project-admin/frontend` directory tree:
        - ./styles/super-tabs-multiline.css
        - ./styles/form-layout-number-field-styles.css
    Check that they exist or are installed. If you use a custom directory for your resource files instead of the default `frontend` folder then make sure it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
```

**Comment by vaadin-miki** [comment] 2022-05-24 12:06
@alabotski thanks for using my components :) or, in this case, trying to use them...

I remember running into this error previously, and I think the solution was to clean all locally generated files (`package.json`, etc.) - but that was in 23.0.6; will check later this week if it is something caused by 23.0.9

**Comment by vaadin-miki** [comment] 2022-07-11 12:43
could not replicate that problem - closing the ticket

if anything like this shows up again, please remove all Vaadin-related generated files (including node-downloaded files and libraries) and do a clean install, as it should solve the problem

**Closed by vaadin-miki** 2022-07-11 12:43 UTC
Labels: bug
