### ISSUE TITLE
Using SuperBigDecimalField as a editor component in a gridpro produces warnings in developer console

### ISSUE THREAD

**Issue by provi-dominik** [vaadin-miki/super-fields#274] opened 2021-02-22 16:22 UTC
If I use a `SuperBigDecimalField` as an editor component in a `GridPro` like this, it produces warnings in the developer cosole every millisecond when I open the view where thie grid is placed:

```
SuperBigDecimalField bigDecimalField = new SuperBigDecimalField();
Column<PvTItemWrapper> editableColumn = gridpro.addEditColumn(Person::getHeight).custom(bigDecimalField, (item, value) -> item.setHeight(value));
```

Here is a screenshot of the warings that are generated:
![image](https://user-images.githubusercontent.com/79461757/108736825-40bee900-7532-11eb-991a-4590b6b14e31.png)

**Comment by vaadin-miki** [comment] 2021-02-22 20:52
thanks for submission! looks like `GridPro` is doing more magic than regular `Grid`... what version of superfields are you using? similar issue #243 has been fixed in 0.9.2, I wonder if it is related

anyway, I just signed up for 14 day trial for GridPro, so I will try to reproduce the issue and hopefully fix it within that period

**Comment by vaadin-miki** [comment] 2021-02-23 10:42
okay, the issue is caused by the fact that the delegate responsible for text selection events is invoked with the real input component not being present; solution to #243 just tells the server to try again (which works with regular grid) - but the component is still not there, which tells the server to try again, and again, and again...

probably the code should check for existence of the frontend component on first use or on visibility change, but that is just a guess

**Comment by vaadin-miki** [comment] 2021-02-23 14:39
well, turns out that what works for `Grid` does not work for `GridPro`, so some of the functionality will be disabled in `GridPro` - the component will stop trying to set up client-initiated text selection events after three failed server attempts; a warning message will be displayed in the logs to highlight the problem

for now, I have no idea on how to properly solve this problem, so a workaround will have to suffice - with it, the component is usable in most ways, text selection problem was moved to #275

**Closed** 2021-02-23 15:57 UTC
Labels: bug

**Comment by provi-dominik** [comment] 2021-02-24 06:43
Can you please tell me, when this workaround is released?

**Comment by vaadin-miki** [comment] 2021-02-24 14:13
it will be released during first week of March, I still need to update to latest Vaadin version (14.4.8)
